FROM nvidia/cuda:11.7.1-devel-ubuntu18.04

RUN apt-get update -y \
    && apt-get install software-properties-common -y\
    && apt-get update \
    && apt install xfonts-utils -y \
    && apt-get install net-tools -y \
    && apt-get install git -y \
    && apt-get install npm -y \
    && apt-get install vim -y \
    && npm install n -g \
    && n stable \
    && apt-get install libgdiplus -y \
    && apt-get install supervisor -y \
    && apt-get install imagemagick -y \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get install python3.9
    # && add-apt-repository ppa:inkscape.dev/stable \
    # && apt-get install inkscape -y

CMD ["/bin/bash"]
